--import Colyseus client
local ColyseusClient = require "colyseus.client"
local cardNamesModule = require "modules.card"  
local zonesModule = require "modules.zones"
local playersModule = require "modules.player"
local cardDataModule = require "modules.cardData"
local turnActionsModule = require "modules.turnActions"

local client
local room
local opponentCards = {}
local gameManager = "/gameManager#gameManager"

-- Connects to the Colyseus server and initializes the game room.
function init(self)
	local BASE_CORE_URL = "wss://ca-yto-4b1a817c.colyseus.cloud:443"
	client = ColyseusClient.new(BASE_CORE_URL)

	client:join_or_create("my_room", {}, handleRoomCreation)
end

-- Callback function to handle the game room creation.
function handleRoomCreation(err, _room)
	if err then
		print("JOIN ERROR: " ..err)
		return
	end

	print("JOIN SUCCESSFUL")
	room = _room

	room:on_message("server-message", function(message)
		print("Server message: " ..message)
	end)

	room:on_message("game-message", handleGameMessage)

	turnActionsModule.drawCard()
	turnActionsModule.drawCard()
	turnActionsModule.drawCard()
	turnActionsModule.drawCard()
	turnActionsModule.drawCard()
end

-- Callback function to handle game messages received from the server.
function handleGameMessage(message)
	print("Game message:")
	for k, v in pairs(message) do
		print(k, v)
	end
	if message.action == "draw" then
		--print("This Players Name is: ", message.player_id)
		playersModule.set_oppId(message.player_id)

		--TODO: make this where drawing happens for both players
		opponent_drawCard()
	elseif message.action == "addOpponentDeck" then
		print("opponent loaded card to deck")
		local card = {
			name = message.cardName,
			cost = message.cardCost,
			power = message.cardPower
		}

		-- TODO: Consider this where both players decks load in locally
		
		table.insert(cardDataModule.opponentDeck, card)

		print("Card added to opponent deck: ", message.cardName)
	elseif message.action == "drop" then
		print('card object: ', message.playedCard)

		local receivedCard = {
			name = message.cardName,
			power = message.cardPower,
			cost = message.cardCost
		}
		print ('		recieved', receivedCard)
		print ('		recieved', message.cardName)

		-- TODO: Consider this where both players played cards load in locally
		
		opponent_drop(message.zone, receivedCard)
	elseif message.action == "end_turn" then


		-- TODO: There is a bug where players can increase energy without both sides
		
		print(' opp ending turn')
		turnActionsModule.oppEndTurn()
	end
end

-- Creates an opponent card in the dropzone at the correct position and updates game manager.

function opponent_drop(zone, playedCard)
	print('card object: ', playedCard)

	local cardsInDropZone = go.get(gameManager, "cardsInZone" .. zone) -- Use the zone to index the property
	local zPos = go.get(gameManager, "zPosition")
	local p = vmath.vector3(128 + ((zone-1)*200) + (cardsInDropZone * 50), 730, zPos)

	go.set(gameManager, "cardsInZone" .. zone, cardsInDropZone + 1) -- Increment the number of cards in the relevant zone

	--opponent card spawning on the board
	local cardGO = factory.create("/spawner#playerCardFactory", p, nil, nil, 0.44)

	cardDataModule.add_opponent_played_card(playedCard)	
	table.insert(cardDataModule.deck, playedCard)	
	cardDataModule.cards[tostring(cardGO)] = playedCard 

	print("Creating card with name:", playedCard.name)
	msg.post(cardGO, "set_name", {name = playedCard.name})
	msg.post(cardGO, "set_cost", {cost = playedCard.cost})
	msg.post(cardGO, "set_power", {power = playedCard.power})
	
	print ("opponent ", playersModule.get_oppId(), " played a card in zone ", zone, ".")
	print ("Card Name: ", playedCard.name)
	print ("Card Cost: ", playedCard.cost)
	print ("Card Power: ", playedCard.power)
	print('Cards in Zone ', zone, ': ', go.get(gameManager, "cardsInZone" .. zone))

	-- Add the card to the zone
	zonesModule.add_opp_card(zone, tostring(cardGO))	
	zonesModule.refresh_zone_tile_power()	

	go.set(gameManager, "zPosition", (zPos + 0.01))

	local cardsInOpponentDeck = go.get(gameManager, "cardsInOpponentDeck")

	if cardsInOpponentDeck > 0 then
		go.delete(opponentCards[cardsInOpponentDeck])
		table.remove(opponentCards, cardsInOpponentDeck)
		go.set(gameManager, "cardsInOpponentDeck", table.getn(opponentCards))
	end

end

-- Creates opponent cards and updates game manager.
function opponent_drawhand()
	for i = 1,5 do
		opponent_drawCard()
	end
end


function opponent_drawCard()
	local opponentHandSize = cardDataModule.getOpponentHandSize()
	local card = factory.create("/spawner#opponentCardBackFactory", vmath.vector3(640 + (opponentHandSize * 10), 1070, 1), nil, nil, 0.2)
	print ("opponent hand size: ", opponentHandSize + 1)
	cardDataModule.addOpponentCardToHandSize()
	
	--cardDataModule.add_opponent_hand(cardName, cardCost, cardPower)
	-- -- cardDataModule.add_opponent_played_card(card)
	-- table.insert(opponentCards, card)
	-- go.set(gameManager, "cardsInOpponentDeck", #opponentCards) -- Using # to get the length of the table
	
	
	print("opponent ", playersModule.get_oppId(), " drew")
end

-- Sends a message to the server when cards are drawn or played.
function on_message(self, message_id, message, sender)
	if message_id == hash("draw") then
		room:send("game-message", {action="draw", player_id=message.player_id})
		print("Cards drawn by player ", message.player_id)
	elseif message_id == hash("drop") then
		room:send("game-message", {action="drop", player_id=message.player_id, zone=message.zone, cardName=message.cardName, cardCost=message.cardCost, cardPower=message.cardPower})
		print(message.cardName," card dropped by player ", message.player_id)
		--print("Card dropped by player ", message.player_id)
	elseif message_id == hash("addOpponentDeck") then
		room:send("game-message", {action="addOpponentDeck", player_id=message.player_id, cardName=message.cardName, cardCost=message.cardCost, cardPower=message.cardPower})
		print("Add Opponent Deck message sent by player ", message.player_id)		
	elseif message_id == hash("end_turn") then
		room:send("game-message", {action="end_turn", player_id=message.player_id})
		print("End turn by player ", message.player_id)
	end
end